/**
 * @file timber.h
 * @version 1.1.1
 * @brief Timber an asynchronous logging library.
 *
 * Timber is a lightweight asynchronous logging library supporting
 * C99 and C++11 or later.
 * You can use stb-style header if you're using C11/C++11 or higher
 * It's generated by bash script named `aux/generate.sh`
 *
 * It uses Dmitry Vyukov bounded MPSC ring buffer with atomics
 * and semaphores for signals between producers and consumer
 *
 * @copyright MIT License
 */
#ifndef TIMBER_H
#define TIMBER_H

#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>

// C/C++ version checking
#if __STDC_VERSION__ >= 199901L
  #define _TIMBER_USING_VALID_C 1
#else
  #if __cplusplus >= 201103L
    #define _TIMBER_USING_VALID_CXX 1
  #endif
#endif

#if !defined(_TIMBER_USING_VALID_C) && !defined(_TIMBER_USING_VALID_CXX)
  #error "Required C or C++ version not found: >=C99 or >=C++11"
#endif

// Define TIMBER_RELEASE or TIMBER_NDEBUG for release builds
#if !defined(TIMBER_RELEASE) && !defined(TIMBER_NDEBUG)
  #define TIMBER_DEBUG 1
#endif

/**
 * @brief Timber version encoded as MAJOR_MINOR_PATCH.
 */
#define TIMBER_VER 10100L

/** @brief Timber major version. */
#define TIMBER_MAJOR 1

/** @brief Timber minor version. */
#define TIMBER_MINOR 1

/** @brief Timber patch version. */
#define TIMBER_PATCH 1

/**
 * @brief Maximum number of sinks that can be attached to a logger.
 */
#define TIMBER_MAX_SINKS 8

/**
 * @brief Maximum size of a single log message.
 * @detail Message in this context is already formatted message.
 * It doesn't mean format string. Also this limitation doesn't effect
 * format on consumer (second step of formatting which is adding level)
 */
#define TIMBER_MAX_MSG_SIZE 256

/**
 * @brief Maximum number of messages processed in a single batch.
 * @detail But, consumer stops batching if there's unready message on the way
 * So this is the limitation for consumer
 */
#define TIMBER_MAX_BATCH 32

/**
 * @brief Number of slots in the asynchronous MPSC queue.
 * @detail This slot includes payload which is
 * level and message (which is can be max 256 bytes long) and
 * Vyukov sequence number
 */
#define TIMBER_QUEUE_SIZE 1024

/**
 * @brief Opaque Timber logger instance.
 *
 * The internal representation is intentionally hidden because the
 * structure contains atomic fields and must remain compatible with
 * C99. Timber provides a STB-style single-header, so the
 * complete structure is visible only in a TU that defines implementation macro.
 *
 * It is recommended to allocate Timber instances on the heap.
 * By default, a Timber instance contains 1024 queue slots. Each slot
 * contains a payload and a sequence number:
 *
 * - Payload: 272 bytes
 * - Slot: 280 bytes
 * - 1024 slots: 286,720 bytes
 * - Queue head and tail: 128 bytes due to cache-line alignment
 * - Complete Timber instance: approximately 287 KB
 *
 * Allocating Timber on the stack can therefore
 * consume a significant amount of stack space.
 *
 * @note timber_init() performs substantially more expensive operations
 * than timber_alloc(), including atomic initialization, semaphore
 * initialization, and thread creation. Therefore, avoiding the
 * allocation performed by timber_alloc() is generally not useful for
 * performance.
 */
typedef struct Timber Timber;

/**
 * @brief Available logging levels.
 * You can add a custom level, the functions will be generated
 * and functions can see your custom level.
 * Because the code depends on this X-Macro
 *
 * To add a new level, put another entry to the list
 * with lowercase and uppercase names of it.
 * Therefore, you can use: TIMBER_CUSTOM constant,
 * timber_customf(), timber_customn() and timber_custom() functions.
 * if level name is custom/CUSTOM.
 */
#define TIMBER_LEVELS \
  X(info, INFO) \
  X(error, ERROR) \
  X(warning, WARNING)

/**
 * @enum TimberLevel
 * @brief Logging severity levels.
 */
typedef enum {
  #define X(_, name) TIMBER_##name,
  TIMBER_LEVELS
  #undef X
  _TimberLevel_count,
} TimberLevel;

/**
 * @enum TimberPolicy
 * @brief Queue-full behavior of the logger.
 */
typedef enum {
  /**
  * @brief Drop the message when the queue is full.
  */
  TIMBER_DROP_POLICY = 0,

  /**
  * @brief Block until one space becomes available in the queue.
  * The producer will wait on empty slots semaphore which
  * is signaled from consumer
  */
  TIMBER_BLOCK_POLICY,

  _TimberPolicy_count,
} TimberPolicy;

#ifdef __cplusplus
  #define TIMBER_EXTERN extern "C"
#else
  #define TIMBER_EXTERN extern
#endif

#ifdef _WIN32
  #define TIMBER_DLLEXPORT __declspec(dllexport)
  #define TIMBER_DLLIMPORT __declspec(dllimport)
#else
  #define TIMBER_DLLEXPORT __attribute__((visibility("default")))
  #define TIMBER_DLLIMPORT
#endif

#ifdef TIMBER_SHARED
  #ifdef TIMBER_BUILD
    #define TIMBER_API TIMBER_DLLEXPORT TIMBER_EXTERN
  #else
    #define TIMBER_API TIMBER_DLLIMPORT TIMBER_EXTERN
  #endif
#else
  #define TIMBER_API TIMBER_EXTERN
#endif

// portable printf-format style checker (only available on gcc and clang)
#if defined(__clang__) || defined(__GNUC__)
  #define TIMBER_PRINTF_LIKE(fmt, args) __attribute__((format(printf, fmt, args)))
#else
  #define TIMBER_PRINTF_LIKE(fmt, args)
#endif

/**
 * @brief Allocates a Timber logger instance.
 *
 * The returned logger must be initialized with timber_init() before
 * it can be used.
 *
 * @return A newly allocated Timber instance, or NULL on allocation failure.
 *
 * @see timber_init()
 * @see timber_free()
 */
TIMBER_API Timber *timber_alloc(void);

/**
 * @brief Initializes a logger instance.
 *
 * @param[in] lg Logger instance to initialize.
 *
 * @return true if initialization succeeds, false otherwise.
 *
 * @note The logger must be initialized before logging or configuring it.
 * @note It'll clean up everything it used on failure.
 */
TIMBER_API bool timber_init(Timber *lg);

/**
 * @brief Logs a message with an explicit message length.
 *
 * @param[in] lg Logger instance.
 * @param[in] level Logging level.
 * @param[in] msg Message buffer.
 * @param[in] msgsz Number of bytes to log from @p msg.
 *
 * @return true if the message was pushed to queue, false otherwise.
 *
 * @note Unlike timber_log(), @p msg does not need to be null-terminated.
 */
TIMBER_API bool timber_logn(Timber *lg, TimberLevel level, const char *msg, size_t msgsz);


/**
 * @brief Logs a null-terminated message.
 *
 * @param[in] lg Logger instance.
 * @param[in] level Logging level.
 * @param[in] msg Null-terminated message.
 *
 * @return true if the message was pushed to queue, false otherwise.
 * @note @p msg MUST BE NULL TERMINATED! Because it calls strlen()
 */
TIMBER_API bool timber_log(Timber *lg, TimberLevel level, const char *msg);


/**
 * @brief Logs a printf-style formatted message.
 *
 * @param[in] lg Logger instance.
 * @param[in] level Logging level.
 * @param[in] fmt printf-style format string.
 * @param[in] ... Arguments referenced by @p fmt.
 *
 * @return true if the message was pushed to queue, false otherwise.
 */
TIMBER_API bool timber_logf(Timber *lg, TimberLevel level, const char *fmt, ...) TIMBER_PRINTF_LIKE(3, 4);

/**
 * @brief Logs a printf-style formatted message using a va_list.
 *
 * @param[in] lg Logger instance.
 * @param[in] level Logging level.
 * @param[in] fmt printf-style format string.
 * @param[in] args Argument list.
 *
 * @return true if the message was pushed to queue, false otherwise.
 */
TIMBER_API bool timber_vlogf(Timber *lg, TimberLevel level, const char *fmt, va_list args) TIMBER_PRINTF_LIKE(3, 0);

/**
 * @brief Destroys a Timber logger.
 *
 * Stops the logger's asynchronous processing and releases resources
 * owned by the logger. (Doesn't free the instance structure)
 *
 * @param[in] lg Logger instance.
 *
 * @return true if destruction succeeds, false otherwise.
 *
 * @see timber_init()
 * @see timber_free()
 */
TIMBER_API bool timber_destroy(Timber *lg);

/**
 * @brief Frees a Timber logger allocated with timber_alloc().
 *
 * @param[in] lg Logger instance.
 *
 * @return true if the logger was successfully freed, false otherwise.
 *
 * @see timber_alloc()
 */
TIMBER_API bool timber_free(Timber *lg);

/**
 * @brief Flushes the current queue
 * Blocks current thread until there're no messages left to process in consumer
 *
 * @param[in] lg Logger instance
 *
 * @return true if logger is alive/valid and all messages flushed out sucessfully false otherwise
*/
TIMBER_API bool timber_flush(Timber *lg);

/**
 * @brief Converts a logging level to its string representation.
 *
 * @param[in] level Logging level.
 *
 * @return Null-terminated string representing @p level.
 */
TIMBER_API const char *timber_level_to_cstr(TimberLevel level);

/**
 * @brief Adds a file sink to a logger.
 *
 * @param[in] lg Logger instance.
 * @param[in] file_path Path of the output file.
 *
 * @return true if the sink was added, false otherwise.
 * @note DO NOT use this after initialization of the instance!
 * **THREAD-UNSAFE**
 */
TIMBER_API bool timber_add_file_sink(Timber *lg, const char *file_path);
/** @brief Alias for timber_add_file_sink */
#define timber_add_file timber_add_file_sink

/**
 * @brief Adds stdout as a logging sink.
 *
 * @param[in] lg Logger instance.
 *
 * @return true if the sink was added, false otherwise.
 * @note DO NOT use this after initialization of the instance!
 * **THREAD-UNSAFE**
 */
TIMBER_API bool timber_add_stdout_sink(Timber *lg);
/** @brief Alias for timber_add_stdout_sink */
#define timber_add_stdout timber_add_stdout_sink

/**
 * @brief Adds stderr as a logging sink.
 *
 * @param[in] lg Logger instance.
 *
 * @return true if the sink was added, false otherwise.
 * @note DO NOT use this after initialization of the instance!
 * **THREAD-UNSAFE**
 */
TIMBER_API bool timber_add_stderr_sink(Timber *lg);
/** @brief Alias for timber_add_stderr_sink */
#define timber_add_stderr timber_add_stderr_sink

/**
 * @brief Sets the queue-full policy of a logger.
 *
 * @param[in] lg Logger instance.
 * @param[in] policy Queue-full policy.
 * @note DO NOT use this after initialization of the instance!
 * **THREAD-UNSAFE**
 */
TIMBER_API void timber_set_policy(Timber *lg, TimberPolicy policy);

/**
 * @brief Sets the output format of a logger. (dummy function)
 * @todo not implemented (doesn't parse anything)
 *
 * @param[in] lg Logger instance.
 * @param[in] format Log format string.
 * @note DO NOT use this after initialization of the instance!
 * **THREAD-UNSAFE**
 */
TIMBER_API void timber_set_format(Timber *lg, const char *format);

/**
 * @brief Generates level-specific logging functions.
 *
 * For every level defined by TIMBER_LEVELS, three functions are generated:
 *
 * - `timber_<level>(Timber *lg)` - logs a null-terminated message.
 * - `timber_<level>n(Timber *lg, const char *msg, size_t size)` - a message with an explicit length.
 * - `timber_<level>f(Timber *lg, const char *fmt, ...)` - a printf-style formatted message.
 *
 * These functions are `static inline` and therefore are not exported
 * as dynamic library symbols.
 *
 * @code
 * timber_info(lg, "Hello");
 * timber_warningn(lg, "Hello!", 6);
 * timber_error(lg, "Something went wrong");
 * timber_warningf(lg, "Value: %d", value);
 * @endcode
 */
#define X(lower, upper)                                                           \
static inline bool timber_##lower##f(Timber *lg, const char *fmt, ...) {          \
  va_list args; va_start(args, fmt);                                              \
  bool ok = timber_vlogf(lg, TIMBER_##upper, fmt, args);                          \
  va_end(args);                                                                   \
  return ok;                                                                      \
}                                                                                 \
static inline bool timber_##lower(Timber *lg, const char *msg) {                  \
  return timber_logn(lg, TIMBER_##upper, msg, strlen(msg));                       \
}                                                                                 \
static inline bool timber_##lower##n(Timber *lg, const char *msg, size_t msgsz) { \
  return timber_logn(lg, TIMBER_##upper, msg, msgsz);                             \
}
TIMBER_LEVELS
#undef X

#endif // TIMBER_H
